# Generated by Django 6.0.1 on 2026-02-13 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0001_initial'),
        ('jardines', '0008_alter_sala_docentes_alter_sala_horario_fin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstructuraFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('programa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estructura_formulario', to='jardines.programa')),
            ],
        ),
        migrations.CreateModel(
            name='CampoFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.CharField(max_length=200)),
                ('nombre_interno', models.SlugField()),
                ('tipo', models.CharField(choices=[('texto', 'Texto corto'), ('textarea', 'Texto largo'), ('numero', 'Número'), ('fecha', 'Fecha'), ('booleano', 'Sí / No'), ('select', 'Lista desplegable')], max_length=20)),
                ('obligatorio', models.BooleanField(default=False)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('opciones', models.TextField(blank=True)),
                ('estructura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='formularios.estructuraformulario')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos', models.JSONField(default=dict)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='formularios.estructuraformulario')),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_formulario', to='alumnos.inscripcion')),
            ],
        ),
    ]
