# Generated by Django 6.0.1 on 2026-02-13 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
        ('formularios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestaformulario',
            name='alumno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_formulario', to='alumnos.alumno'),
        ),
        migrations.AlterField(
            model_name='respuestaformulario',
            name='inscripcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_formulario', to='alumnos.inscripcion'),
        ),
    ]
