# Generated by Django 5.2.6 on 2026-03-20 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0007_alter_asistencia_options_and_more'),
        ('formularios', '0002_respuestaformulario_alumno_and_more'),
        ('jardines', '0010_alter_jardin_sector'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campoformulario',
            options={'ordering': ['orden'], 'verbose_name': 'Campo de Formulario', 'verbose_name_plural': 'Campos de Formulario'},
        ),
        migrations.AlterModelOptions(
            name='respuestaformulario',
            options={'verbose_name': 'Respuesta de Formulario', 'verbose_name_plural': 'Respuestas de Formulario'},
        ),
        migrations.AlterField(
            model_name='campoformulario',
            name='etiqueta',
            field=models.CharField(help_text='Nombre visible para el usuario.', max_length=200),
        ),
        migrations.AlterField(
            model_name='campoformulario',
            name='nombre_interno',
            field=models.SlugField(help_text='Identificador único del campo (sin espacios ni caracteres especiales).'),
        ),
        migrations.AlterField(
            model_name='campoformulario',
            name='opciones',
            field=models.TextField(blank=True, help_text="Solo para 'select': valores separados por coma (ej: Opción 1, Opción 2)."),
        ),
        migrations.AlterField(
            model_name='campoformulario',
            name='orden',
            field=models.PositiveIntegerField(default=0, help_text='Posición relativa del campo en el formulario.'),
        ),
        migrations.AlterField(
            model_name='campoformulario',
            name='tipo',
            field=models.CharField(choices=[('texto', 'Texto corto'), ('textarea', 'Texto largo'), ('numero', 'Número'), ('fecha', 'Fecha'), ('booleano', 'Sí / No (Checkbox)'), ('select', 'Lista desplegable')], max_length=20),
        ),
        migrations.AlterField(
            model_name='estructuraformulario',
            name='activo',
            field=models.BooleanField(default=True, help_text='Define si el formulario debe mostrarse en la carga de alumnos.'),
        ),
        migrations.AlterField(
            model_name='estructuraformulario',
            name='programa',
            field=models.OneToOneField(help_text='Programa al que pertenece esta configuración de campos.', on_delete=django.db.models.deletion.CASCADE, related_name='estructura_formulario', to='jardines.programa'),
        ),
        migrations.AlterField(
            model_name='respuestaformulario',
            name='alumno',
            field=models.ForeignKey(blank=True, help_text='Vinculación con el legajo definitivo del alumno.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_formulario', to='alumnos.alumno'),
        ),
        migrations.AlterField(
            model_name='respuestaformulario',
            name='datos',
            field=models.JSONField(default=dict, help_text="Diccionario con pares {'nombre_interno': valor}."),
        ),
        migrations.AlterField(
            model_name='respuestaformulario',
            name='inscripcion',
            field=models.ForeignKey(blank=True, help_text='Vinculación opcional con una ficha de pre-inscripción.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_formulario', to='alumnos.inscripcion'),
        ),
    ]
