# Generated by Django 5.2.3 on 2025-07-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardines', '0003_sala_responsable'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='salas',
            field=models.ManyToManyField(blank=True, related_name='docentes_asignados', to='jardines.sala'),
        ),
    ]
