# Generated by Django 5.2.1 on 2025-06-09 14:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='dni',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='El DNI debe tener el formato XX.XXX.XXX', regex='^\\d{2}\\.\\d{3}\\.\\d{3}$')]),
        ),
    ]
