# Generated by Django 6.0.1 on 2026-01-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='es_docente',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='salas',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('directivo', 'Directivo'), ('docente', 'Docente')], default='docente', max_length=20),
        ),
    ]
