# Generated by Django 6.0.1 on 2026-02-04 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_usuario_dni_remove_usuario_es_docente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('coordinador', 'Coordinador'), ('docente', 'Docente')], default='docente', max_length=20),
        ),
    ]
