# Generated by Django 6.0.1 on 2026-02-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='dni',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='DNI / Pasaporte'),
        ),
    ]
