# Generated by Django 5.2.6 on 2026-03-20 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardines', '0010_alter_jardin_sector'),
        ('users', '0006_accionauditoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='programas_asignados',
            field=models.ManyToManyField(blank=True, help_text='Programas sobre los cuales un Coordinador tiene gestión.', related_name='coordinadores', to='jardines.programa'),
        ),
    ]
