# Generated by Django 5.2.6 on 2026-07-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_usuario_programas_asignados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('coordinador', 'Coordinador'), ('docente', 'Docente'), ('auxiliar', 'Auxiliar')], default='docente', max_length=20),
        ),
    ]
