# Generated by Django 5.2.1 on 2025-06-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jardin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
                ('subprograma', models.CharField(choices=[('Centros Educativos Infantiles Municipales', 'centros educativos infantiles municipales'), ('Salas Cuna', 'salas cuna')])),
                ('coordenadas', models.CharField(blank=True, max_length=100)),
                ('sector', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('turno', models.CharField(choices=[('mañana', 'Mañana'), ('tarde', 'Tarde')])),
                ('horarios', models.TimeField()),
            ],
        ),
    ]
