# Generated by Django 6.0.1 on 2026-01-23 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('turno', models.CharField(choices=[('M', 'Mañana'), ('T', 'Tarde'), ('J', 'Jornada Completa')], max_length=10)),
                ('horario_inicio', models.TimeField(default='08:00', max_length=5)),
                ('horario_fin', models.TimeField(default='12:00', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Subprograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Jardin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.TextField(max_length=150)),
                ('coordenadas', models.CharField(blank=True, max_length=100)),
                ('sector', models.CharField(choices=[('Norte', 'norte'), ('Sur', 'sur'), ('Este', 'este'), ('Oeste', 'oeste'), ('Centro', 'centro')], max_length=100)),
                ('programa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jardines', to='jardines.programa')),
            ],
        ),
    ]
