# Generated by Django 5.2.3 on 2025-07-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jardin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.TextField(max_length=100)),
                ('subprograma', models.CharField(choices=[('Centros Educativos Infantiles Municipales', 'centros educativos infantiles municipales'), ('Salas Cuna', 'salas cuna')], max_length=100)),
                ('coordenadas', models.CharField(blank=True, max_length=100)),
                ('sector', models.CharField(choices=[('Norte', 'norte'), ('Sur', 'sur'), ('Este', 'este'), ('Oeste', 'oeste'), ('Centro', 'centro')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('turno', models.CharField(choices=[('mañana', 'Mañana'), ('tarde', 'Tarde')], max_length=10)),
                ('horario_inicio', models.TimeField(default='08:00', max_length=5)),
                ('horario_fin', models.TimeField(default='12:00', max_length=5)),
            ],
        ),
    ]
