# Generated by Django 5.2.1 on 2025-06-03 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jardines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='docentes',
            field=models.ManyToManyField(related_name='salas_asignadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sala',
            name='jardin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jardines.jardin'),
        ),
    ]
