# Generated by Django 6.0.1 on 2026-01-23 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jardines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='docentes',
            field=models.ManyToManyField(blank=True, related_name='salas_como_docente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sala',
            name='jardin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salas', to='jardines.jardin'),
        ),
        migrations.AddField(
            model_name='sala',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subprograma',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subprogramas', to='jardines.programa'),
        ),
        migrations.AddField(
            model_name='jardin',
            name='subprograma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='jardines.subprograma'),
        ),
        migrations.AlterUniqueTogether(
            name='subprograma',
            unique_together={('programa', 'nombre')},
        ),
    ]
