# Generated by Django 6.0.1 on 2026-01-27 19:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardines', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='docentes',
            field=models.ManyToManyField(blank=True, limit_choices_to={'rol': 'docente'}, related_name='salas_asignadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
