# Generated by Django 5.2.1 on 2025-06-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardines', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jardin',
            name='sector',
            field=models.CharField(choices=[('Norte', 'norte'), ('Sur', 'sur'), ('Este', 'este'), ('Oeste', 'oeste'), ('Centro', 'centro')]),
        ),
    ]
