# Generated by Django 6.0.1 on 2026-01-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardines', '0003_alter_sala_docentes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='turno',
            field=models.CharField(choices=[('mañana', 'Mañana'), ('tarde', 'Tarde')], max_length=20),
        ),
    ]
