# Generated by Django 5.2.1 on 2025-06-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardines', '0003_alter_jardin_sector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sala',
            name='horarios',
        ),
        migrations.AddField(
            model_name='sala',
            name='horario_fin',
            field=models.TimeField(default='12:00'),
        ),
        migrations.AddField(
            model_name='sala',
            name='horario_inicio',
            field=models.TimeField(default='08:00'),
        ),
    ]
