# Generated by Django 6.0.1 on 2026-02-01 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardines', '0004_alter_sala_turno'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programa',
            options={'verbose_name': 'Programa', 'verbose_name_plural': 'Programas'},
        ),
        migrations.AlterModelOptions(
            name='subprograma',
            options={'verbose_name': 'Subprograma', 'verbose_name_plural': 'Subprogramas'},
        ),
        migrations.AddField(
            model_name='programa',
            name='usa_formulario_ampliado',
            field=models.BooleanField(default=False, help_text='Marca si este programa requiere el formulario ampliado de inscripción'),
        ),
        migrations.AddField(
            model_name='subprograma',
            name='usa_formulario_ampliado',
            field=models.BooleanField(default=False, help_text='Marca si este subprograma requiere formulario ampliado'),
        ),
    ]
