# Generated by Django 6.0.1 on 2026-02-01 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jardines', '0005_alter_programa_options_alter_subprograma_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jardin',
            options={'verbose_name': 'Espacio', 'verbose_name_plural': 'Espacios'},
        ),
    ]
