# Generated by Django 6.0.1 on 2026-02-13 13:25

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardines', '0007_alter_sala_responsable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='docentes',
            field=models.ManyToManyField(blank=True, related_name='salas_asignadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sala',
            name='horario_fin',
            field=models.TimeField(default='12:00'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='horario_inicio',
            field=models.TimeField(default='08:00'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='jardin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salas', to='jardines.jardin'),
        ),
        migrations.AddConstraint(
            model_name='sala',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nombre'), models.F('jardin'), models.F('turno'), name='unique_sala_por_jardin_turno'),
        ),
    ]
