# Generated by Django 6.0.1 on 2026-02-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardines', '0008_alter_sala_docentes_alter_sala_horario_fin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jardin',
            name='telefono',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
