# Generated by Django 5.2.6 on 2026-03-20 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardines', '0009_jardin_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jardin',
            name='sector',
            field=models.CharField(choices=[('Norte', 'Norte'), ('Sur', 'Sur'), ('Este', 'Este'), ('Oeste', 'Oeste'), ('Centro', 'Centro')], max_length=100),
        ),
    ]
