# Generated by Django 5.2.6 on 2026-05-14 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardines', '0010_alter_jardin_sector'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenciaDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('P', 'Presente'), ('A', 'Ausente'), ('J', 'Justificado'), ('T', 'Llegada Tarde'), ('R', 'Retiro Temprano')], max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias_docente', to=settings.AUTH_USER_MODEL)),
                ('jardin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias_docentes', to='jardines.jardin')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias_docentes_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asistencia de Docente',
                'verbose_name_plural': 'Asistencias de Docentes',
                'ordering': ['-fecha', 'docente__last_name'],
                'unique_together': {('docente', 'jardin', 'fecha')},
            },
        ),
    ]
