# Generated by Django 5.2.6 on 2026-05-14 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardines', '0011_asistenciadocente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asistenciadocente',
            options={'ordering': ['-fecha', '-hora_ingreso', 'docente__last_name'], 'verbose_name': 'Asistencia de Docente', 'verbose_name_plural': 'Asistencias de Docentes'},
        ),
        migrations.AddField(
            model_name='asistenciadocente',
            name='hora_ingreso',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asistenciadocente',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asistenciadocente',
            name='estado',
            field=models.CharField(choices=[('P', 'Presente'), ('A', 'Ausente'), ('J', 'Justificado'), ('T', 'Llegada Tarde'), ('R', 'Retiro Temprano')], default='P', max_length=20),
        ),
        migrations.AlterField(
            model_name='asistenciadocente',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias_docentes_registradas', to=settings.AUTH_USER_MODEL),
        ),
    ]
