# Generated by Django 5.2.6 on 2026-05-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardines', '0012_alter_asistenciadocente_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistenciadocente',
            name='fuera_de_jornada',
            field=models.BooleanField(default=False),
        ),
    ]
