# Generated by Django 5.2.6 on 2026-06-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardines', '0013_asistenciadocente_fuera_de_jornada'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistenciadocente',
            name='fichado',
            field=models.BooleanField(default=False, verbose_name='Fichado'),
        ),
        migrations.AddField(
            model_name='asistenciadocente',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='asistenciadocente',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud'),
        ),
        migrations.AddField(
            model_name='programa',
            name='prefijo_comprobante',
            field=models.CharField(default='BC', help_text='Prefijo utilizado para generar los números de comprobantes (ej: EA, EC)', max_length=10, verbose_name='Prefijo Comprobante'),
        ),
    ]
