# Generated by Django 5.2.6 on 2026-06-17 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardines', '0014_asistenciadocente_fichado_asistenciadocente_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='domingo',
            field=models.BooleanField(default=False, verbose_name='Domingo'),
        ),
        migrations.AddField(
            model_name='sala',
            name='jueves',
            field=models.BooleanField(default=True, verbose_name='Jueves'),
        ),
        migrations.AddField(
            model_name='sala',
            name='lunes',
            field=models.BooleanField(default=True, verbose_name='Lunes'),
        ),
        migrations.AddField(
            model_name='sala',
            name='martes',
            field=models.BooleanField(default=True, verbose_name='Martes'),
        ),
        migrations.AddField(
            model_name='sala',
            name='miercoles',
            field=models.BooleanField(default=True, verbose_name='Miércoles'),
        ),
        migrations.AddField(
            model_name='sala',
            name='sabado',
            field=models.BooleanField(default=False, verbose_name='Sábado'),
        ),
        migrations.AddField(
            model_name='sala',
            name='subprograma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salas', to='jardines.subprograma', verbose_name='Subprograma'),
        ),
        migrations.AddField(
            model_name='sala',
            name='viernes',
            field=models.BooleanField(default=True, verbose_name='Viernes'),
        ),
    ]
