# Generated by Django 5.2.6 on 2026-06-18 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

# Global list to store data in memory between operations
MIGRATED_DATA = []

def backup_existing_docentes(apps, schema_editor):
    from django.db import connection
    with connection.cursor() as cursor:
        try:
            cursor.execute("SELECT sala_id, usuario_id FROM jardines_sala_docentes")
            rows = cursor.fetchall()
            for sala_id, usuario_id in rows:
                MIGRATED_DATA.append((sala_id, usuario_id))
        except Exception:
            pass

def restore_migrated_docentes(apps, schema_editor):
    Sala = apps.get_model('jardines', 'Sala')
    AsignacionDocenteSala = apps.get_model('jardines', 'AsignacionDocenteSala')
    db_alias = schema_editor.connection.alias
    
    for sala_id, usuario_id in MIGRATED_DATA:
        try:
            sala = Sala.objects.using(db_alias).get(id=sala_id)
            AsignacionDocenteSala.objects.using(db_alias).get_or_create(
                sala_id=sala_id,
                docente_id=usuario_id,
                defaults={
                    'lunes': sala.lunes,
                    'martes': sala.martes,
                    'miercoles': sala.miercoles,
                    'jueves': sala.jueves,
                    'viernes': sala.viernes,
                    'sabado': sala.sabado,
                    'domingo': sala.domingo,
                }
            )
        except Exception:
            pass

class Migration(migrations.Migration):

    dependencies = [
        ('jardines', '0015_sala_domingo_sala_jueves_sala_lunes_sala_martes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(backup_existing_docentes, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='sala',
            name='docentes',
        ),
        migrations.CreateModel(
            name='AsignacionDocenteSala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lunes', models.BooleanField(default=True, verbose_name='Lunes')),
                ('martes', models.BooleanField(default=True, verbose_name='Martes')),
                ('miercoles', models.BooleanField(default=True, verbose_name='Miércoles')),
                ('jueves', models.BooleanField(default=True, verbose_name='Jueves')),
                ('viernes', models.BooleanField(default=True, verbose_name='Viernes')),
                ('sabado', models.BooleanField(default=False, verbose_name='Sábado')),
                ('domingo', models.BooleanField(default=False, verbose_name='Domingo')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_salas', to=settings.AUTH_USER_MODEL)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_docentes', to='jardines.sala')),
            ],
            options={
                'verbose_name': 'Asignación de Docente a Sala',
                'verbose_name_plural': 'Asignaciones de Docentes a Salas',
                'unique_together': {('docente', 'sala')},
            },
        ),
        migrations.AddField(
            model_name='sala',
            name='docentes',
            field=models.ManyToManyField(blank=True, related_name='salas_asignadas', through='jardines.AsignacionDocenteSala', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(restore_migrated_docentes, reverse_code=migrations.RunPython.noop),
    ]
