# Generated by Django 5.2.6 on 2026-06-22 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardines', '0015_sala_domingo_sala_jueves_sala_lunes_sala_martes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistenciadocente',
            name='estado',
            field=models.CharField(choices=[('P', 'Presente'), ('A', 'Ausente'), ('J', 'Justificado'), ('T', 'Llegada Tarde'), ('R', 'Retiro Temprano'), ('L', 'Ausente por licencia')], default='P', max_length=20),
        ),
        migrations.CreateModel(
            name='LicenciaDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_licencia', models.CharField(choices=[('enfermedad', 'Enfermedad'), ('maternidad_paternidad', 'Maternidad / Paternidad'), ('familiar_cargo', 'Familiar a cargo'), ('estudio_capacitacion', 'Estudio y capacitación'), ('razones_particulares', 'Razones particulares'), ('duelo', 'Duelo'), ('matrimonio', 'Matrimonio'), ('sangre_organos', 'Donación de sangre u órganos'), ('gremial', 'Gremial'), ('otro', 'Otro')], max_length=50, verbose_name='Tipo de licencia')),
                ('motivo', models.TextField(verbose_name='Motivo / Descripción')),
                ('fecha_desde', models.DateField(verbose_name='Fecha desde')),
                ('fecha_hasta', models.DateField(verbose_name='Fecha hasta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licencias_creadas', to=settings.AUTH_USER_MODEL)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licencias', to=settings.AUTH_USER_MODEL, verbose_name='Docente')),
                ('reemplazante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reemplazos', to=settings.AUTH_USER_MODEL, verbose_name='Docente reemplazante')),
            ],
            options={
                'verbose_name': 'Licencia de Docente',
                'verbose_name_plural': 'Licencias de Docentes',
                'ordering': ['-fecha_desde', 'docente__last_name'],
            },
        ),
    ]
