# Generated by Django 5.2.6 on 2026-06-29 13:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardines', '0017_merge_0016'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asistenciadocente',
            options={'ordering': ['-fecha', 'turno', 'docente__last_name'], 'verbose_name': 'Asistencia de Docente', 'verbose_name_plural': 'Asistencias de Docentes'},
        ),
        migrations.AlterUniqueTogether(
            name='asistenciadocente',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='asistenciadocente',
            name='turno',
            field=models.CharField(blank=True, choices=[('mañana', 'Mañana'), ('tarde', 'Tarde')], max_length=20, null=True, verbose_name='Turno'),
        ),
        migrations.AlterUniqueTogether(
            name='asistenciadocente',
            unique_together={('docente', 'jardin', 'turno', 'fecha')},
        ),
    ]
