# Generated by Django 5.2.6 on 2026-07-24 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardines', '0018_asistenciadocente_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistenciadocente',
            name='jardin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asistencias_docentes', to='jardines.jardin', verbose_name='Espacio / Jardín'),
        ),
    ]
