# Generated by Django 5.2.6 on 2026-08-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardines', '0019_allow_null_jardin_asistencia_docente'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistenciadocente',
            name='fichado_salida',
            field=models.BooleanField(default=False, verbose_name='Fichado Salida'),
        ),
        migrations.AddField(
            model_name='asistenciadocente',
            name='hora_salida',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Salida'),
        ),
        migrations.AddField(
            model_name='asistenciadocente',
            name='ip_address_salida',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Salida'),
        ),
        migrations.AddField(
            model_name='asistenciadocente',
            name='latitude_salida',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud Salida'),
        ),
        migrations.AddField(
            model_name='asistenciadocente',
            name='longitude_salida',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud Salida'),
        ),
    ]
