# Generated by Django 5.2.6 on 2026-08-21 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardines', '0020_asistenciadocente_fichado_salida_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoActividadEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del tipo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('es_default', models.BooleanField(default=False, verbose_name='Tipo predeterminado')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tipo de Actividad Especial',
                'verbose_name_plural': 'Tipos de Actividades Especiales',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='asistenciadocente',
            name='estado',
            field=models.CharField(choices=[('P', 'Presente'), ('A', 'Ausente'), ('J', 'Justificado'), ('T', 'Llegada Tarde'), ('R', 'Retiro Temprano'), ('L', 'Ausente por licencia'), ('E', 'Actividad Especial / Exento')], default='P', max_length=20),
        ),
        migrations.CreateModel(
            name='ActividadEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la actividad')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de fin')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción / Observaciones')),
                ('alcance', models.CharField(choices=[('programa', 'Programa completo'), ('jardin', 'Espacio / Jardín'), ('sala', 'Salas específicas'), ('docente', 'Docentes puntuales')], default='docente', max_length=20, verbose_name='Alcance de asignación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('docentes', models.ManyToManyField(blank=True, related_name='actividades_especiales', to=settings.AUTH_USER_MODEL, verbose_name='Docentes afectados')),
                ('jardin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actividades_especiales', to='jardines.jardin', verbose_name='Espacio / Jardín')),
                ('programa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actividades_especiales', to='jardines.programa', verbose_name='Programa')),
                ('salas', models.ManyToManyField(blank=True, related_name='actividades_especiales', to='jardines.sala', verbose_name='Salas afectadas')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actividades', to='jardines.tipoactividadespecial', verbose_name='Tipo de actividad')),
            ],
            options={
                'verbose_name': 'Actividad Especial',
                'verbose_name_plural': 'Actividades Especiales',
                'ordering': ['-fecha', 'hora_inicio', 'nombre'],
            },
        ),
    ]
