# Generated by Django 5.2.6 on 2026-08-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardines', '0022_crear_tipos_actividad_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividadespecial',
            name='turno_afectado',
            field=models.CharField(choices=[('todo_el_dia', 'Todo el día (Mañana y Tarde)'), ('mañana', 'Turno Mañana'), ('tarde', 'Turno Tarde')], default='todo_el_dia', max_length=20, verbose_name='Turno exento de clases habituales'),
        ),
    ]
