# Generated by Django 5.2.6 on 2026-08-21 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_reemplazantes_forward(apps, schema_editor):
    try:
        LicenciaDocente = apps.get_model('jardines', 'LicenciaDocente')
        ReemplazanteLicencia = apps.get_model('jardines', 'ReemplazanteLicencia')
        for lic in LicenciaDocente.objects.all():
            if hasattr(lic, 'reemplazante') and lic.reemplazante_id:
                ReemplazanteLicencia.objects.get_or_create(
                    licencia=lic,
                    reemplazante_id=lic.reemplazante_id
                )
    except Exception:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('jardines', '0023_actividadespecial_turno_afectado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='licenciadocente',
            name='turno_licencia',
            field=models.CharField(blank=True, choices=[('manana', 'Mañana'), ('tarde', 'Tarde')], help_text='Dejar vacío si la licencia afecta a todos los turnos del docente.', max_length=10, null=True, verbose_name='Turno afectado'),
        ),
        migrations.CreateModel(
            name='ReemplazanteLicencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reemplazantes_licencia', to='jardines.licenciadocente')),
                ('reemplazante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reemplazos_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Docente reemplazante')),
                ('sala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reemplazos', to='jardines.sala', verbose_name='Sala a cubrir')),
            ],
            options={
                'verbose_name': 'Reemplazante de Licencia',
                'verbose_name_plural': 'Reemplazantes de Licencia',
                'unique_together': {('licencia', 'reemplazante')},
            },
        ),
        migrations.RunPython(migrate_reemplazantes_forward, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='licenciadocente',
            name='reemplazante',
        ),
    ]

