# Generated by Django 5.2.6 on 2026-09-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardines', '0024_remove_licenciadocente_reemplazante_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostoDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(db_index=True, max_length=20, verbose_name='DNI / CUIL (Limpio)')),
                ('mes', models.CharField(db_index=True, help_text='Formato YYYY-MM (ej: 2026-03)', max_length=7, verbose_name='Mes / Período')),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Costo Laboral ($)')),
                ('origen', models.CharField(default='GoogleSheets', max_length=50, verbose_name='Origen de Datos')),
                ('actualizado_el', models.DateTimeField(auto_now=True, verbose_name='Última Sincronización')),
            ],
            options={
                'verbose_name': 'Costo Docente',
                'verbose_name_plural': 'Costos Docentes',
                'unique_together': {('dni', 'mes')},
            },
        ),
    ]
