# Generated by Django 5.2.6 on 2026-06-05 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0011_justificaciones_y_bajas'),
        ('jardines', '0013_asistenciadocente_fuera_de_jornada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Importe')),
                ('fecha_pago', models.DateField(verbose_name='Fecha de Pago')),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia')], max_length=20, verbose_name='Método de Pago')),
                ('estado', models.CharField(choices=[('pagado', 'Pagado'), ('adeuda', 'Adeuda')], default='pagado', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='alumnos.alumno', verbose_name='Alumno')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='jardines.programa', verbose_name='Programa')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado Por')),
                ('sala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='jardines.sala', verbose_name='Sala')),
                ('subprograma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='jardines.subprograma', verbose_name='Subprograma')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_pago', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgramaCobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe_mensual', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Importe Mensual')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('programa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_cobro', to='jardines.programa', verbose_name='Programa')),
            ],
            options={
                'verbose_name': 'Programa con Cobro',
                'verbose_name_plural': 'Programas con Cobro',
            },
        ),
        migrations.CreateModel(
            name='ResponsableCobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('titular', 'Titular'), ('suplente', 'Suplente')], default='titular', max_length=20, verbose_name='Rol')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsables_cobro', to='jardines.programa', verbose_name='Programa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsabilidades_cobro', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Responsable de Cobro',
                'verbose_name_plural': 'Responsables de Cobro',
                'unique_together': {('usuario', 'programa')},
            },
        ),
    ]
