# Generated by Django 5.2.6 on 2026-06-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='anio_pagado',
            field=models.IntegerField(default=2026, verbose_name='Año Pagado'),
        ),
        migrations.AddField(
            model_name='pago',
            name='mes_pagado',
            field=models.IntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], default=6, verbose_name='Mes Pagado'),
        ),
    ]
