# Generated by Django 5.2.6 on 2026-06-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0002_pago_anio_pagado_pago_mes_pagado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='correo_envio',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo de envío'),
        ),
        migrations.AddField(
            model_name='pago',
            name='enviar_correo',
            field=models.BooleanField(default=False, verbose_name='Enviar por correo'),
        ),
    ]
