# Generated by Django 5.2.6 on 2026-07-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0003_pago_correo_envio_pago_enviar_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='mes_pagado',
            field=models.IntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], default=7, verbose_name='Mes Pagado'),
        ),
    ]
