# Generated by Django 6.0.1 on 2026-02-03 19:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jardines', '0006_alter_jardin_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoJustificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='El DNI debe tener el formato XX.XXX.XXX', regex='^\\d{2}\\.\\d{3}\\.\\d{3}$')])),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jardines.sala')),
            ],
        ),
        migrations.CreateModel(
            name='FichaProgramaAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sabe_leer', models.BooleanField(blank=True, null=True)),
                ('sabe_escribir', models.BooleanField(blank=True, null=True)),
                ('nivel_educativo', models.CharField(blank=True, max_length=100)),
                ('situacion_laboral', models.CharField(blank=True, max_length=100)),
                ('asistencia_social', models.BooleanField(blank=True, null=True)),
                ('observaciones_programa', models.TextField(blank=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('escolaridad', models.CharField(blank=True, max_length=100)),
                ('obra_social', models.CharField(blank=True, max_length=100)),
                ('alumno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha_programa', to='alumnos.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('nivel_educativo', models.CharField(blank=True, max_length=100)),
                ('situacion_laboral', models.CharField(blank=True, max_length=100)),
                ('tiene_obra_social', models.BooleanField(blank=True, null=True)),
                ('restricciones_fisicas', models.TextField(blank=True)),
                ('experiencia_previa', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jardines.jardin')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jardines.programa')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jardines.sala')),
                ('subprograma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jardines.subprograma')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(max_length=50)),
                ('estado', models.CharField(choices=[('P', 'Presente'), ('A', 'Ausente'), ('J', 'Justificado')], max_length=20)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='alumnos.alumno')),
                ('docente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('motivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alumnos.motivojustificacion')),
            ],
            options={
                'unique_together': {('alumno', 'fecha')},
            },
        ),
    ]
