# Generated by Django 5.2.1 on 2025-06-03 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0001_initial'),
        ('jardines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jardines.sala'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.alumno'),
        ),
    ]
