# Generated by Django 6.0.1 on 2026-02-13 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscripcion',
            name='experiencia_previa',
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='nivel_educativo',
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='restricciones_fisicas',
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='situacion_laboral',
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='tiene_obra_social',
        ),
    ]
