# Generated by Django 6.0.1 on 2026-01-23 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='docente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='motivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alumnos.motivojustificacion'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='tutores',
            field=models.ManyToManyField(blank=True, related_name='alumnos', to='alumnos.tutor'),
        ),
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together={('alumno', 'fecha')},
        ),
    ]
