# Generated by Django 6.0.1 on 2026-02-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_remove_inscripcion_experiencia_previa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='tutores',
            field=models.ManyToManyField(blank=True, related_name='alumnos', to='alumnos.tutor'),
        ),
    ]
