# Generated by Django 5.2.1 on 2025-06-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='fecha_alta',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
