# Generated by Django 5.2.3 on 2025-08-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='estado',
            field=models.CharField(choices=[('P', 'Presente'), ('A', 'Ausente'), ('J', 'Justificado')], max_length=20),
        ),
    ]
