# Generated by Django 6.0.1 on 2026-02-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_alumno_tutores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='estado',
            field=models.CharField(choices=[('P', 'Presente'), ('A', 'Ausente'), ('J', 'Justificado'), ('T', 'Tarde')], max_length=20),
        ),
    ]
