# Generated by Django 6.0.1 on 2026-02-18 13:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0004_alter_asistencia_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='dni',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='El DNI solo puede contener números, puntos o guiones.', regex='^[\\d\\.-]+$')]),
        ),
    ]
