# Generated by Django 6.0.1 on 2026-02-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0005_alter_tutor_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='estado',
            field=models.CharField(choices=[('P', 'Presente'), ('A', 'Ausente'), ('J', 'Justificado'), ('T', 'Llegada Tarde'), ('R', 'Retiro Temprano')], max_length=20),
        ),
    ]
