# Generated by Django 5.2.6 on 2026-03-20 00:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0006_alter_asistencia_estado'),
        ('jardines', '0010_alter_jardin_sector'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asistencia',
            options={'verbose_name': 'Asistencia', 'verbose_name_plural': 'Asistencias'},
        ),
        migrations.AlterModelOptions(
            name='motivojustificacion',
            options={'verbose_name': 'Motivo de Justificación', 'verbose_name_plural': 'Motivos de Justificación'},
        ),
        migrations.AlterModelOptions(
            name='tutor',
            options={'verbose_name': 'Tutor', 'verbose_name_plural': 'Tutores'},
        ),
        migrations.AlterField(
            model_name='alumno',
            name='activo',
            field=models.BooleanField(default=True, help_text='Si está False, el alumno se considera dado de baja.'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='dni',
            field=models.CharField(help_text='DNI sin puntos ni espacios.', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='fecha_baja',
            field=models.DateField(blank=True, help_text='Fecha en la que el alumno dejó de asistir.', null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='sala',
            field=models.ForeignKey(help_text='Sala actual del alumno.', on_delete=django.db.models.deletion.PROTECT, to='jardines.sala'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='tutores',
            field=models.ManyToManyField(blank=True, help_text='Responsables legales o tutores.', related_name='alumnos', to='alumnos.tutor'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='docente',
            field=models.ForeignKey(help_text='Docente que registró la asistencia.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='motivo',
            field=models.ForeignKey(blank=True, help_text='Motivo obligatorio si el estado es Justificado, opcional para Tarde o Retiro.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='alumnos.motivojustificacion'),
        ),
    ]
