# Generated by Django 5.2.6 on 2026-04-10 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0007_alter_asistencia_options_and_more'),
        ('jardines', '0010_alter_jardin_sector'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='jardines.sala'),
        ),
        migrations.CreateModel(
            name='AsignacionSala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el alumno sigue cursando en esta sala.')),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('fecha_baja', models.DateField(blank=True, help_text='Fecha de egreso o abandono en esta sala particular.', null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='alumnos.alumno')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alumnos_asignados', to='jardines.sala')),
            ],
            options={
                'verbose_name': 'Asignación a Sala',
                'verbose_name_plural': 'Asignaciones a Salas',
                'unique_together': {('alumno', 'sala')},
            },
        ),
    ]
