# Generated by Django 5.2.6 on 2026-04-10 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0008_alter_asistencia_unique_together_asistencia_sala_and_more'),
        ('jardines', '0010_alter_jardin_sector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='fecha_baja',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='sala',
        ),
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together={('alumno', 'sala', 'fecha')},
        ),
    ]
