# Generated by Django 5.2.6 on 2026-04-13 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0009_remove_alumno_activo_remove_alumno_fecha_baja_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='email',
        ),
    ]
