# Generated by Django 5.2.6 on 2026-04-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0010_remove_tutor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionsala',
            name='motivo_baja',
            field=models.TextField(blank=True, help_text='Motivo por el que se dio de baja.'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='observaciones',
            field=models.CharField(blank=True, help_text="Texto libre para especificar justificación si se selecciona 'Otro' o aclaraciones extra.", max_length=255),
        ),
    ]
